[versions]
# libraries
junit = "4.13.2"
langchain4j = "1.9.0"
opentest4j = "1.3.0"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.4"
kotlin = "2.2.21"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
langchain4j = { group = "dev.langchain4j", name = "langchain4j", version.ref = "langchain4j" }
langchain4j-openai = { group = "dev.langchain4j", name = "langchain4j-open-ai", version.ref = "langchain4j" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }